### ISSUE TITLE
No passwords found in config file

### ISSUE THREAD

**Issue by ghost** [rclone/passwordcheck#1]
passwordcheck v1.0.1

When running this utility on a config file where the password isn't generated by rclone the output can be a bit confusing. Without using -verbose this is what you get:

`No passwords found in config file - did you use the right file?`

But if you run it with -verbose it's a bit more clear what is actually happening:

`###########: obscured password password = "####################"  was not generated by rclone: illegal base64 data at input byte 7`

**Comment by ncw** [comment]
Hmm, yes that wording isn't quite right is it.

The tool is discarding passwords which can't have been generated by `rclone config` but not counting them as found passwords.

I'll have a think.

**Comment by ncw** [comment]
I've added a stats block like this

    found 269 remote definitions
    found 54 passwords generated by rclone config which need checking
    ignored 11 passwords not generated by rclone config
    ignored 14 passwords less than 64 bits

which will be printed after the tool has parsed the config file which should make it clearer.

I've also changed the message to

    No passwords to check found in config file - did you use the right file?

**Comment by ncw** [comment]
This was released in v1.0.2
